---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - endpoints
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - services/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.openeverest.io
  resources:
  - instances
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.openeverest.io
  resources:
  - instances/finalizers
  verbs:
  - update
- apiGroups:
  - core.openeverest.io
  resources:
  - instances/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - core.openeverest.io
  resources:
  - providers
  verbs:
  - get
  - list
  - watch
