apiVersion: v2
name: provider-huawei-elb
description: A Helm chart for deploying the OpenEverest provider-huawei-elb provider
type: application
version: 0.1.0
appVersion: "0.1.0"
keywords:
  - openeverest
  - provider
  - database
home: https://github.com/openeverest/provider-huawei-elb
sources:
  - https://github.com/openeverest/provider-huawei-elb
maintainers:
  - name: OpenEverest Contributors
# TODO: If your provider depends on an operator Helm chart, add it here.
# dependencies:
#   - name: my-operator
#     version: "1.0.0"
#     repository: https://example.com/helm-charts/
